# -----------------------------------------------------------------------------
#
# Motion control common makefile definitions
# 
# Original Author: Stephan Fegan
# $Author: sfegan $
# $Date: 2007/10/20 02:03:37 $
# $Revision: 1.1 $
# $Tag$
#
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# CHILA DEFINES AND INCLUDES
# -----------------------------------------------------------------------------

MCDEFFLAGS = -D__STDC_LIMIT_MACROS \
		-D__STDC_CONSTANT_MACROS \
		-D_FILE_OFFSET_BITS=64 \
		-D_LARGEFILE_SOURCE

MCLIBS = -lMotionControl

# -----------------------------------------------------------------------------
# Compiler/Linker Options
# -----------------------------------------------------------------------------

################################## INTEL C++ ##################################
#CXX = /opt/intel_cc_80/bin/icc
#CXXFLAGS = -g -xN -O3 -Wall $(INCLUDE_DIRS)
#LDFLAGS = -static -g -Kc++ -xN -O3 -Wall $(LIB_DIRS)

################################### GNU C++ ###################################

ifndef OPTFLAGS
OPTFLAGS = -O2 -g
endif

ifndef CXX
CXX = g++
endif
CXXFLAGS = $(OPTFLAGS) -Wall $(MCDEFFLAGS) 
LDFLAGS = $(OPTFLAGS) -Wall 
#CXXFLAGS = -g -fno-default-inline -fno-inline -m32 -Wall $(INCLUDE_DIRS) $(DEFINES)
#LDFLAGS = -static -g -fno-default-inline -fno-inline -m32 -Wall $(LIB_DIRS)
#LDFLAGS = -g -fno-default-inline -fno-inline -m32 -Wall $(LIB_DIRS)
